---
title: "Developing Data Products Application - Coursera"
author: "Mehul Patel"
date: "February 15, 2016"
output: html_document
---


Welcome to the "Select the best car for your trip" app, that was developed for the Developing Data Products Course, from Coursera. This app helps you to choose a car for a trip, using the mtcars dataset from [R].

First, you need to inform the distance of your trip and the price of gasoline in your region. These information will be used to calculate the Gasoline Expenditure for each car in the dataset. Then, you can enter the maximum amount of money you want to spend on gasoline, and the table shows only the cars that have Miles per Gallon (mpg) that can go below this value.

Second, you can choose some caractheristcs of the cars that you desire: Cylinders, Displacement, Horse Power and Transmission. The table will show only the cars with the filters selected. You can sort the table according to the variable you want by clicking the arrows at the top of the table.

Source code for ui.R and server.R files are available on the [Github](https://github.com/mehulpatel21)