library(dplyr)
NEI <- readRDS("summarySCC_PM25.rds")
NEI <- filter(NEI, fips == "24510")
NEI <- summarize(group_by(NEI, year), Emissions=sum(Emissions))
with(NEI, plot(year, Emissions, pch=19, xlab="Years", ylab="PM2.5 Emission", main="PM2.5 Emission Vs Years"))
model <- lm(Emissions ~ year, NEI)
abline(model, lwd=2)
dev.copy(png, file="plot2.png")
dev.off()